Lint/UselessAssign:
  Description: Disallows useless variable assignments
  ExcludeTypeDeclarations: false
  Excluded:
  - src/werk/commands/plan.cr
  - src/werk/commands/run.cr
  - src/werk/application.cr
  Enabled: true
