version: "1"

description: "Manage Werk with Werk"

jobs:
  main:
    description: Run all checks and build the application
    executor: local
    needs:
      - build:*

  lint:crystal:
    description: Lint the Crystal codebase
    executor: docker
    image: ghcr.io/crystal-ameba/ameba:${TAG}
    variables:
      TAG: latest
    commands:
      - ameba

  lint:dockerfile:
    description: Lint the Dockerfile
    executor: docker
    image: hadolint/hadolint:${TAG}
    variables:
      TAG: v2.14.0-debian
    commands:
      - hadolint -V Dockerfile

  test:
    description: Test the codebase
    executor: local
    commands:
      - crystal spec
    needs:
      - lint:*

  build:local:
    description: Build the application
    executor: local
    commands:
      - shards install --ignore-crystal-version
      - shards build
    needs:
      - test

  build:docker:
    description: Build the Docker image
    executor: local
    commands:
      - >
        docker build
        --tag werk 
        --build-arg RELEASE=
        --no-cache .
    needs:
      - test

  docs:
    description: Generate API documentation
    executor: local
    commands:
      - crystal docs
      - open docs/index.html

  # --- Install application locally
  install:
    description: Install the application locally
    executor: local
    commands:
      - shards build
      - cp ./bin/werk $HOME/bin/werk
