version: "1"

description: "Manage Werk with Werk"

jobs:
  main:
    description: "Build application"
    executor: local
    needs:
      - build:local

  build:
    executor: local
    needs:
      - build:local
      - build:docker

  build:local:
    executor: local
    commands:
      - shards install --ignore-crystal-version
      - shards build
    needs:
      - qa

  build:docker:
    description: Docker build
    executor: local
    commands:
      - docker build -t werk .
    needs:
      - qa

  qa:
    description: Linters and tests
    executor: local
    needs:
      - lint
      - test

  lint:
    description: "Lint everything"
    executor: local
    needs:
      - lint:crystal
      - lint:dockerfile

  lint:crystal:
    description: "Lint code"
    executor: docker
    image: ghcr.io/crystal-ameba/ameba:latest
    commands:
      - ameba

  lint:dockerfile:
    description: Lint Dockerfile
    executor: local
    commands:
      - hadolint Dockerfile

  test:
    description: "Test code"
    executor: local
    commands:
      - crystal spec

  docs:
    description: Generate API documentation
    executor: local
    commands:
      - crystal docs
      - open docs/index.html

  install:
    description: Install Werk locally
    executor: local
    commands:
      - echo "Installing locally..."
      - sudo cp -v ./bin/werk /usr/local/bin
    needs:
      - main

  uninstall:
    description: Uninstall Werk locally
    executor: local
    variables:
      APP: /usr/local/bin/werk
    commands:
      - '[[ -f "${APP}" ]] && sudo rm -vf "${APP}" || echo "Werk is not installed!"'