require "spec"
require "yaml"
require "json"
require "uuid"
require "log"
require "dotenv"
require "colorize"
require "digest/md5"
require "wait_group"

require "../src/craph"
require "../src/docr"
require "../src/tools"
require "../src/vault"
require "../src/template"

require "../src/werk/error"
require "../src/werk/config/*"
require "../src/werk/config/jobs/*"
require "../src/werk/utils/*"
require "../src/werk/context"
require "../src/werk/schedulers/*"
require "../src/werk/executors/*"
require "../src/werk/pipeline"

Werk::Utils::PrefixIO.enabled = false
