name: CD

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          - os: macos-latest
            asset: werk-darwin-arm64
          - os: ubuntu-latest
            asset: werk-linux-amd64

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.19.1

      - name: Additional Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev yq

      - name: Additional macOS dependencies
        if: contains(matrix.os, 'macos')
        run: brew install openssl yq

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update shard version
        run: yq eval -i ".version = \"${{ github.event.release.tag_name }}\"" shard.yml

      - name: Install dependencies
        run: shards install --production --ignore-crystal-version

      - name: Build
        if: contains(matrix.os, 'macos')
        run: shards build --release --no-debug
        env:
          APP_VERSION: ${{ github.event.release.tag_name }}

      - name: Build static
        if: contains(matrix.os, 'ubuntu')
        run: shards build --release --no-debug --static
        env:
          APP_VERSION: ${{ github.event.release.tag_name }}

      - name: Upload application
        id: upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bin/werk
          asset_name: ${{ matrix.asset }}
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Homebrew formula update
        uses: mislav/bump-homebrew-formula-action@v1.12
        if: contains(matrix.os, 'macos')
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
        with:
          formula-name: werk
          homebrew-tap: marghidanu/homebrew-werk
          base-branch: master

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update shard version
        run: yq eval -i ".version = \"${{ github.event.release.tag_name }}\"" shard.yml

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: APP_VERSION=${{ github.event.release.tag_name }}
          tags: ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }},ghcr.io/${{ github.repository }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
