name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  schedule:
    - cron: 0 23 * * *

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hadolint
        uses: brpaz/hadolint-action@v1.1.0

      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.19.1

      - name: Install dependencies
        run: shards install --ignore-crystal-version

      - name: Ameba
        run: crystal run bin/ameba.cr

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: 1.19.1

      - name: Additional Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep -Po '"tag_name": "v\K[^"]+')
          wget -qO- "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" | sudo tar xz -C /usr/local/bin gitleaks

      - name: Additional macOS dependencies
        if: contains(matrix.os, 'macos')
        run: brew install openssl gitleaks

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: shards install --ignore-crystal-version

      - name: Run tests
        run: crystal spec

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
          cache-to: type=inline
